In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
a=np.array([[1,2],[3,4]])

In [6]:
a

array([[1, 2],
       [3, 4]])

In [7]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(3.0)

array([0., 1., 2.])

In [9]:
np.arange(0.0,5.0,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [12]:
np.zeros(5,dtype=int,order="F")

array([0, 0, 0, 0, 0])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.zeros((2,3),order="F")

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.linspace(1,10)#bydefault num=50

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [19]:
np.linspace(2.0,3.0,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [20]:
np.linspace(2.0,3.0,num=5,endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [21]:
np.linspace(1,100,num=4,retstep=True)#give the diff

(array([  1.,  34.,  67., 100.]), 33.0)

In [22]:
np.eye(3)# bydefault row=column so (3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.eye(2,3)#(n,m)=(row,column)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [24]:
np.eye(4,k=-1)#down side to main diagonal bcz k=-1

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [25]:
np.eye(4,k=2)#up side to main diagonal bcz k=2

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.eye(4,5,k=-1,dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [27]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [28]:
np.random.rand(3)

array([0.35199028, 0.54609917, 0.07793935])

In [29]:
np.random.randn(3)

array([-1.01251865,  0.66087813, -0.9321908 ])

In [2]:
np.random.randint(3,size=10)#give random value of 0,1,2

array([1, 2, 0, 1, 1, 1, 0, 0, 0, 1])

In [8]:
np.random.randint(2,size=10)#give random value of 0,1

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1])

In [7]:
np.random.randint(1,size=20)#all zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.random.randint(5,size=(4,5))#give 2d array with 1 to 4 random value

array([[4, 3, 4, 2, 2],
       [2, 3, 1, 1, 4],
       [0, 4, 4, 3, 1],
       [1, 0, 1, 1, 0]])

In [34]:
a=np.array([1,2,4,5])

In [35]:
a.ndim

1

In [36]:
a.shape

(4,)

In [37]:
a.size

4

In [38]:
a.dtype

dtype('int32')

In [39]:
a.itemsize#(dtype/8) 1byte=8bit

4

In [40]:
a=np.array([[1,2,4,6,7],[1,5,83,75]])#give array with list

C:\Users\yash\AppData\Local\Temp\ipykernel_8052\154263765.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array([[1,2,4,6,7],[1,5,83,75]])#give array with list


In [41]:
a

array([list([1, 2, 4, 6, 7]), list([1, 5, 83, 75])], dtype=object)

In [42]:
a=np.array([[1,2.5,4,6,7],[1,5,83,75,45]])

In [43]:
a

array([[ 1. ,  2.5,  4. ,  6. ,  7. ],
       [ 1. ,  5. , 83. , 75. , 45. ]])

In [44]:
a.ndim

2

In [45]:
a.shape

(2, 5)

In [46]:
a.size

10

In [47]:
a.dtype

dtype('float64')

In [48]:
a.itemsize#dtype/8

8

In [49]:
a=np.array([1,2,3,4,5])

In [50]:
a

array([1, 2, 3, 4, 5])

In [51]:
a[0]

1

In [52]:
a[4]

5

In [53]:
#a[6] error

In [54]:
a[-1]

5

In [55]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [56]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [57]:
a[0][0]

1

In [58]:
a[0][1]

2

In [59]:
a[-2][-1]

5

In [60]:
a[0][4]

5

In [61]:
a=np.array([1,2,3,4.5,6,7])

In [62]:
a

array([1. , 2. , 3. , 4.5, 6. , 7. ])

In [63]:
a[2:5]

array([3. , 4.5, 6. ])

In [64]:
a[1:]

array([2. , 3. , 4.5, 6. , 7. ])

In [65]:
a[:3]

array([1., 2., 3.])

In [66]:
a[:]

array([1. , 2. , 3. , 4.5, 6. , 7. ])

In [67]:
a=np.array([[1,2],[3,4],[5,6]])

In [68]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [69]:
a[1:,1:]

array([[4],
       [6]])

In [70]:
a[1,0:]

array([3, 4])

In [71]:
a[1:,0:]

array([[3, 4],
       [5, 6]])

In [72]:
a=np.array([[1,2,3,4],[5,6,7,8],[8,9,10,11]])

In [73]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9, 10, 11]])

In [74]:
a[:1,:2]

array([[1, 2]])

In [75]:
a[1:,3:]

array([[ 8],
       [11]])

In [76]:
a[::,::2]#(all row)(skip 1,3 column)(slicing):)

array([[ 1,  3],
       [ 5,  7],
       [ 8, 10]])

In [77]:
a=np.arange(1,10)

In [78]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
index=np.array([1,4,5])

In [80]:
a[index]

array([2, 5, 6])

In [81]:
a[[1,4,5]]#we can also use this

array([2, 5, 6])

In [82]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [83]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
a[[1,1,2],[0,2,1]]#if i want 4,6,8 so it is simple first indentify all row and cloumn(row,column)

array([4, 6, 8])

In [85]:
a=np.array([[1,-1,0],[0,-3,2]])

In [86]:
a[a<1]

array([-1,  0,  0, -3])

In [87]:
a[a<1]*2

array([-2,  0,  0, -6])

In [88]:
a=np.arange(1,5)

In [89]:
a

array([1, 2, 3, 4])

In [90]:
a+2

array([3, 4, 5, 6])

In [91]:
a*3

array([ 3,  6,  9, 12])

In [92]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [93]:
a-1

array([0, 1, 2, 3])

In [94]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [95]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [96]:
b=np.array([3,4,5,6])

In [97]:
b

array([3, 4, 5, 6])

In [98]:
a+b

array([ 4,  6,  8, 10])

In [99]:
a-b

array([-2, -2, -2, -2])

In [100]:
a*b

array([ 3,  8, 15, 24])

In [101]:
 a=np.arange(10)

In [102]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
np.reshape(a,(5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [104]:
np.reshape(a,(5,2),order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [105]:
a=np.arange(5)

In [106]:
a

array([0, 1, 2, 3, 4])

In [107]:
np.resize(a,(2,4))#repeat value from begining

array([[0, 1, 2, 3],
       [4, 0, 1, 2]])

In [108]:
np.resize(a,(5,2))

array([[0, 1],
       [2, 3],
       [4, 0],
       [1, 2],
       [3, 4]])

In [109]:
a.resize((5,2),refcheck=False)#remaining value take as 0

In [110]:
a

array([[0, 1],
       [2, 3],
       [4, 0],
       [0, 0],
       [0, 0]])

In [111]:
a=np.array([[1,2,3],[3,4,5]])

In [112]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [113]:
a.flatten()#retrun a copy

array([1, 2, 3, 3, 4, 5])

In [114]:
a.flatten(order='F')

array([1, 3, 2, 4, 3, 5])

In [115]:
a=np.array([[1,2],[3,4]])

In [116]:
a

array([[1, 2],
       [3, 4]])

In [117]:
a.ravel()#view of copy

array([1, 2, 3, 4])

In [118]:
a=np.arange(1,11).reshape(5,2)

In [119]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [120]:
np.transpose(a)#row to column and column to row(only for 2d array)

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [121]:
a=np.array([[1,2],[3,4]])

In [122]:
a

array([[1, 2],
       [3, 4]])

In [123]:
np.swapaxes(a,0,1)

array([[1, 3],
       [2, 4]])

In [124]:
a=np.arange(1,5)

In [125]:
a

array([1, 2, 3, 4])

In [126]:
b=np.arange(4,9)

In [127]:
b

array([4, 5, 6, 7, 8])

In [128]:
np.concatenate((a,b))#dimension must be same

array([1, 2, 3, 4, 4, 5, 6, 7, 8])

In [129]:
c=np.zeros(9,dtype=int)# why 9 bcz our cocate array has 9 value so 

In [130]:
c

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [131]:
np.concatenate((a,b),out=c)# so my concate array store on c 

array([1, 2, 3, 4, 4, 5, 6, 7, 8])

In [132]:
c

array([1, 2, 3, 4, 4, 5, 6, 7, 8])

In [143]:
a=np.arange(1,11)

In [144]:
np.split(a,5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [145]:
a=np.arange(0,6)

In [146]:
np.insert(a,2,10)#to insert with specific index and value

array([ 0,  1, 10,  2,  3,  4,  5])

In [147]:
a=np.array([[1,2],[3,4]])

In [148]:
np.insert(a,2,10)#it gives 2d array to 1d and after insert value

array([ 1,  2, 10,  3,  4])

In [154]:
np.insert(a,2,10,axis=0)#write axis=0 so we get 2d array and it is row inserting bcz of axis=0

array([[ 1,  2],
       [ 3,  4],
       [10, 10]])

In [155]:
np.insert(a,0,10,axis=0)

array([[10, 10],
       [ 1,  2],
       [ 3,  4]])

In [156]:
np.insert(a,1,10,axis=0)

array([[ 1,  2],
       [10, 10],
       [ 3,  4]])

In [157]:
np.insert(a,2,10,axis=1)#now it is column inserting bcz of axis=1

array([[ 1,  2, 10],
       [ 3,  4, 10]])

In [158]:
np.insert(a,1,[5,6])

array([1, 5, 6, 2, 3, 4])

In [159]:
np.insert(a,1,[5,6],axis=0)

array([[1, 2],
       [5, 6],
       [3, 4]])

In [160]:
np.insert(a,1,[5,6],axis=1)

array([[1, 5, 2],
       [3, 6, 4]])

In [161]:
a=np.arange(1,5)

In [162]:
a

array([1, 2, 3, 4])

In [163]:
np.append(a,10)

array([ 1,  2,  3,  4, 10])

In [172]:
a=np.array([[1,2],[3,4]])

In [173]:
a

array([[1, 2],
       [3, 4]])

In [174]:
np.append(a,[10,10])

array([ 1,  2,  3,  4, 10, 10])

In [177]:
np.append(a,[[10,10]],axis=0)

array([[ 1,  2],
       [ 3,  4],
       [10, 10]])

In [179]:
np.append(a,[[10],[10]],axis=1)

array([[ 1,  2, 10],
       [ 3,  4, 10]])

In [180]:
a=np.arange(1,6)

In [181]:
np.delete(a,2)

array([1, 2, 4, 5])

In [189]:
a=np.array([[1,2],[3,4]])

In [190]:
b=np.array([[10,20],[30,40]])

In [192]:
a+b

array([[11, 22],
       [33, 44]])

In [193]:
a*b#normal multiplication

array([[ 10,  40],
       [ 90, 160]])

In [194]:
a.dot(b)#matrix multiplication

array([[ 70, 100],
       [150, 220]])

In [200]:
a=np.matrix("1 2;3 4")

In [201]:
a

matrix([[1, 2],
        [3, 4]])

In [202]:
b=np.matrix([[10,20],[30,40]])

In [203]:
b

matrix([[10, 20],
        [30, 40]])

In [211]:
c=np.linalg.inv(a)#matrix inverse

In [212]:
c

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [209]:
np.linalg.inv(b)

matrix([[-0.2 ,  0.1 ],
        [ 0.15, -0.05]])

In [210]:
np.allclose(a,c)

False

In [213]:
np.linalg.matrix_power(a,2)

matrix([[ 7, 10],
        [15, 22]])

In [214]:
a=np.array([[3,1],[1,2]])#3x+y=9,x+2y=8 solver

In [215]:
a

array([[3, 1],
       [1, 2]])

In [217]:
b=np.array([[9],[8]])

In [218]:
b

array([[9],
       [8]])

In [219]:
np.linalg.solve(a,b)

array([[2.],
       [3.]])

In [220]:
a=np.array([[1,2],[3,4]])

In [221]:
a

array([[1, 2],
       [3, 4]])

In [228]:
np.linalg.det(a)#ad-bc

-2.0000000000000004

In [229]:
np.linalg.det(a).round(2)

-2.0